name: "Vprofile Actions CI/CD Pipeline"
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: vprofileapp
  K8S_CLUSTER_NAME: vprofile-eks

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Maven Test
        run: mvn test

      - name: Checkstyle Analysis
        run: mvn checkstyle:checkstyle
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

        # SonarQube Analysis
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Analysis
        run: sonar-scanner
          -Dsonar.host.url=${{secrets.SONAR_URL }}
          -Dsonar.login=${{secrets.SONAR_TOKEN }}
          -Dsonar.projectKey=${{secrets.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{secrets.SONAR_ORGANIZATION }}
          -Dsonar.sources=src/
          -Dsonar.junit.reportPaths=target/surefire-reports
          -Dsonar.jacoco.reportPaths=target/jacoco.exec
          -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
          -Dsonar.java.binaries=target/test-classes/com/visualpathit/account

      - name: Sonarqube Quality Gate Check
        id: sonarqube_quality_gate_check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt

  Build_and_Publish:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
          repo: ${{ env.ECR_REPOSITORY }}
          region: ${{ env.AWS_REGION }}
          tags: latest,${{ github.run_number }}
          daemon_off: false
          dockerfile: ./Dockerfile
          context: ./

  Deploy_to_EKS:
    needs: Build_and_Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials for EKS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.K8S_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Print kubeconfig
        run: cat ~/.kube/config

      - name: Login to ECR
        id: login-ecr
        run: kubectl create secret docker-registry ecr-registry-secret --docker-server=${{ secrets.REGISTRY }} --docker-username=AWS --docker-password=$(aws ecr get-login-password --region ${{ env.AWS_REGION }}) --namespace default || echo "Secret already exists"

      - name: Deploy Helm
        uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          cluster-name: ${{ env.K8S_CLUSTER_NAME }}
          # config-files: .github/values/dev.yaml
          chart-path: helm/vprofilecharts
          namespace: default
          values: appimage=${{ secrets.REGISTRY }}/${{ env.ECR_REPOSITORY }},apptag=${{ github.run_number }}
          name: vprofile-stack
